### PR TITLE
Mobile Nav - vertical positioning fix, burger & logo

### PR DESCRIPTION
**Pull request by andrewborstein**
Hey thur. I think the nav bar height changed when the logo was swapped, and the vertical alignment was off a wee bit. So I just centered the logo and mobile menu trigger (burger) icon.

### CODE REVIEW

**Comment by goldenmeanie** [comment]
That reminds me. DEATH TO BURGERS!

**Comment by andrewborstein** [comment]
Ha. I'm totally down to murder this burger. Just need to appease my OCD and vertically align whatever's in its place.

**Comment by goldenmeanie** [comment]
Understood, Swap it to "MENU" and align. I'll merge it immediately : )

**Comment by andrewborstein** [comment]
Your death wish is my burger killing command.

**Pull request merged**
